### ISSUE TITLE
Facebook share button not working correctly

### ISSUE THREAD

**Issue by pierorex** [openbudgets/participatory-budgeting#10]
![image](https://cloud.githubusercontent.com/assets/9373636/24957368/d616a7f0-1f8b-11e7-9eca-99f015b6af0b.png)
This message is shown in the window opened when trying to share a vote summary through Facebook.
I think you have to update the redirect or domain url in Facebook's app configuration to allow http://localhost:3000 to be redirected to.

**Comment by esebastian** [comment]
With the introduction of the ability to provide a custom Facebook app ID by setting the value of an environment variable in #38, this shouldn't be a problem anymore, as anyone can configure her own Facebook app (and its URLs) for sharing.

@pierorex Does it makes sense to you?
