### ISSUE TITLE
Add support for translations

### ISSUE THREAD

**Issue by dcabo** [openbudgets/participatory-budgeting#13]
The application is currently available in English, but the pilots need it to be translated to Spanish.

**Comment by skarampatakis** [comment]
We would like also translation in Greek for the Greek Pilot. Please inform on how we can contribute on this.

**Comment by esebastian** [comment]
Sounds great @skarampatakis. Once the i18n infrastructure is in place, it will be a matter of translate some text files. It would be great if you guys can take care of that.

**Comment by skarampatakis** [comment]
Hi @esebastian,
Could you please elaborate on how to edit the translations? If I understand correctly we should modify participatory-budgeting/config/locales/gettext/el/app.po file? Is this the only one?

**Comment by esebastian** [comment]
Hi @skarampatakis,
That would do it, but we've configured the [translation.io](https://translation.io/civio/openbudgets/es) service for a more convenient approach, as it offers a nice web interface for team collaboration and automatic resource synchronization. I've just added you to the translation project, you should receive an invitation shortly.
