### ISSUE TITLE
Improve sign in form fields

### ISSUE THREAD

**Issue by rauldiazpoblete** [openbudgets/participatory-budgeting#24]
Birthdate format is not defined, maybe we must separate this in 3 different fields (day, month, year).
We also need an explanation & format validation in field document (DNI, NIE, ...).

**Comment by esebastian** [comment]
Sign in fields are actually dynamic on a per deployment basis, except the email one. Specifically, these too are only presented to the users in the Torrelodones pilot.

Currently, we automatically infer the number and name of the fields from the information stored in the `voter_secrets` table, but I guess it would be I good idea to include these kind of info (including not only name, but probably type and format) in some sort of 'theme' settings.

**Comment by dcabo** [comment]
We need to discuss and implement a long-term solution with proper custom formatting, based on the field type. But that won't be ready for the Torrelodones pilot, starting in 5 days. As a temporary solution we should add some sentences about the expected format and/or samples. The city has asked for this too.

@esebastian, can you do this or do you need @rauldiazpoblete help?

**Comment by esebastian** [comment]
I've added more detail to the field labels, and we're also parsing the value in the date field to allow the usual European formats (`%d/%m/%Y`, `%d-%m-%Y`, `%Y/%m/%d` and `%Y-%m-%d`).

@dcabo @rauldiazpoblete Looks good to you?:
![screen shot 2017-05-26 at 10 55 20](https://cloud.githubusercontent.com/assets/577074/26489513/f6bfcb3c-4207-11e7-91d3-fad4ff3834ec.png)

**Comment by dcabo** [comment]
About the dates, that's great.

On the document id, maybe we should add a note ("write your id as 1234X..."). How hard would that be? Would it make sense (not now, long term) to have an optional description/help text for each field?

**Comment by esebastian** [comment]
The problem with the document field is that there are some different formats:
D.N.I.: 53713184D, 279793B, ...
Tarjeta de residencia: X07323369A, Y01927564M, ...
Pasaporte/otros docs.: 98661X, 08-VU-2160/16, ...

I've taken the idea of the "NIF / NIE / Pasaporte" from the Bankia online access sign in form: https://www.bankia.es/es/particulares/acceso-clientes

Anyway, it wouldn't be hard to add a note if there's a better option.
