### ISSUE TITLE
Decimal seperator in different locales

### ISSUE THREAD

**Issue by skarampatakis** [openbudgets/participatory-budgeting#46]
When locale is set to "el", amounts are presented in the respective locale. That means ie 15.000,100 €. So far so good. 
![image](https://user-images.githubusercontent.com/2419820/27131594-024e49e0-5114-11e7-8570-1ffde2bcc291.png)

But if you edit the proposal through admin panel and then save, ```.``` is perceived as decimal separator and ```,``` as grouping character, thus changing the amount. When you save, the above amount will be changed to 15€!

![image](https://user-images.githubusercontent.com/2419820/27131619-1bd60678-5114-11e7-978a-fed9b8a883d8.png)

![image](https://user-images.githubusercontent.com/2419820/27131633-30052c96-5114-11e7-9d66-dc90b4e9de20.png)

PS: I have not edited the amount in any case.

**Comment by esebastian** [comment]
@skarampatakis It's a bug, thanks for pointing it out.
