### ISSUE TITLE
NoMethodError in Admin::Proposals#index

### ISSUE THREAD

**Issue by skarampatakis** [openbudgets/participatory-budgeting#52]
Hi,
I have update the app to the latest commit. 
Then tried to create a new proposal through the admin panel, and I get the following error after I submit the new proposal.

```
NoMethodError in Admin::Proposals#index
Showing /home/participatory-budget/participatory-budgeting/app/views/partials/admin/_proposal-item.html.haml where line #27 raised:

undefined method `closed?' for nil:NilClass
```

Then the admin page is no more accessible, but I can get the voting and monitoring view.

**Comment by skarampatakis** [comment]
I checked the database and it seems that it does not get a campaign ID.

**Comment by skarampatakis** [comment]
And managed to bypass it by manually setting the campaing_id to an existing campaing ID.

**Comment by esebastian** [comment]
Thanks for the report @skarampatakis, we'll take a look.
