### ISSUE TITLE
Production deployment documentation

### ISSUE THREAD

**Issue by skarampatakis** [openbudgets/participatory-budgeting#55]
Currently documentation covers dev and local testing deployment isntructions. Are there any instructions for production deployment? Recommended server etc?

**Comment by esebastian** [comment]
Production environments may differ wildly depending on specific needs and expected workloads, so it is difficult to provide specific server requirements.

For the pilots we've been using [Heroku](https://devcenter.heroku.com/articles/getting-started-with-rails5) and Digital Ocean [droplets](https://www.digitalocean.com/community/tutorials/how-to-use-the-ruby-on-rails-one-click-application-on-digitalocean).

Deployment to systems like Heroku is usually a matter of pushing the repo to a given remote,  and for regular servers the Capistrano task is provided.

If you need some specific guidance, feel free to contact me directly.

**Comment by skarampatakis** [comment]
I have done some work with docker, which I think will be our preffered method for deployment, whenever it is required. You can find it on our repo if you want to check it. https://github.com/okgreece/participatory-budgeting/tree/feature/docker. We could make some modifications and create a PR if you think is useful.

**Comment by esebastian** [comment]
That would be great indeed, @skarampatakis! We'll be looking forward for that PR!
