### ISSUE TITLE
Admin Role

### ISSUE THREAD

**Issue by skarampatakis** [openbudgets/participatory-budgeting#6]
Hi,
I am testing the platform locally. I have noticed that in order to access the admin panel your email have to belong on civio.es domain. Shouldn't this be configurable?

**Comment by esebastian** [comment]
Yes, indeed. We were waiting until the pilots started so we could take into account their preferences. Our preferences were in the line of having the configuration to be a part of the deployment process (environment variable, config file, ...) in order to keep the tool as simple as possible.
