### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by pierorex** [openbudgets/participatory-budgeting#8]
Hi, guys. 
I found a problem when installing the tool, it was in the `db:create` command. PostgreSQL was complaining that there was no role called `piero` which is my username in my machine, so I went and created a role with my name in Postgres and made it superuser to be able to go through the installation.

I don't know if being superuser is mandatory, but I think it would be awesome if you could update the Readme to reflect that the developer should create a role for his account inside Postgres before trying to create the db.

**Comment by esebastian** [comment]
I guess that the expected role depends on the actual PostgreSQL installation. In local instances it usually creates a role named after the username and that's what Rails expects by default in development environments, all without further configuration. Nevertheless, you're right and some more info about the setup of the required components would be nice.
